version: "2"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - UMASK_SET=022
      - VIRTUAL_HOST=syncthing.localhost
      - VIRTUAL_PORT=8384
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
    network_mode: "bridge"
